using System;
using System.Collections.Generic;

namespace FF3DContexts.OracleModels
{
    public partial class Woreq
    {
        public string Requestnum { get; set; }
        public DateTime Datereleased { get; set; }
        public DateTime? Timereleased { get; set; }
        public string Requestedby { get; set; }
        public DateTime? Requestdate { get; set; }
        public DateTime? Requesttime { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Finishdate { get; set; }
        public decimal? Priority { get; set; }
        public string Wotype { get; set; }
        public decimal? Estduration { get; set; }
        public string Phone { get; set; }
        public string Ext { get; set; }
        public string Faxnum { get; set; }
        public string Assignedto { get; set; }
        public string Tasknum { get; set; }
        public string Taskdesc { get; set; }
        public string Selected { get; set; }
        public DateTime? Updatestamp { get; set; }
        public string Updateuser { get; set; }
        public string Siteid { get; set; }
        public string Email { get; set; }
        public string Pagernum { get; set; }
        public decimal? Convnum { get; set; }
        public decimal? Presaincarico { get; set; }
        public string Urgenza { get; set; }
        public string Urgclienti { get; set; }
        public decimal? Importo { get; set; }
        public string Richallcod { get; set; }
        public string Ricgestmankey { get; set; }
        public string Statogestman { get; set; }
        public string Classificazione { get; set; }
        public decimal? Idrichgestman { get; set; }
        public string Reparto { get; set; }
        public string Referente { get; set; }
        public string Cliente { get; set; }
        public string Guasto { get; set; }
        public string Note { get; set; }
        public string DispLocali { get; set; }
        public string PartiEdili { get; set; }
        public string Componenti { get; set; }
        public string Macchinari { get; set; }
        public string Stampafile { get; set; }
        public string Faxauto { get; set; }
        public string Tecnicoc { get; set; }
        public string StatoInvio { get; set; }
        public string FileInvio { get; set; }
        public string Codicepe { get; set; }
        public string Codicecomp { get; set; }
        public string Codicemac { get; set; }
        public string Operatorecc { get; set; }
        public string Codicemac2 { get; set; }
        public string Inserrato { get; set; }
        public string Ext2 { get; set; }
        public DateTime? Dataprevin { get; set; }
        public DateTime? Dataricprev { get; set; }
        public string Stato { get; set; }
        public string Inviamail { get; set; }
        public DateTime? Schedstartdate { get; set; }
        public DateTime? Schedstarttime { get; set; }
        public string Fee { get; set; }
        public string Macroatt { get; set; }
        public DateTime? Schedfinishdate { get; set; }
        public DateTime? Schedfinishtime { get; set; }
        public string Ntelrich { get; set; }
        public string Motivoannullamento { get; set; }
        public string Percorso { get; set; }
        public string Origine { get; set; }
        public string Tiporichiedente { get; set; }
        public DateTime? Datarifprev { get; set; }
        public DateTime? Orarifprev { get; set; }
        public DateTime? Dataprevconsprev { get; set; }
        public DateTime? Oraprevconsprev { get; set; }
        public string Incidente { get; set; }
        public DateTime? Dataprocesso { get; set; }
        public DateTime? Oraprocesso { get; set; }
        public string Motivorifiuto { get; set; }
        public DateTime? Datasosp { get; set; }
        public DateTime? Orasosp { get; set; }
        public string Motivososp { get; set; }
        public string Codiceati { get; set; }
        public string Mp2pal { get; set; }
        public DateTime? DataDiffSms { get; set; }
        public string Prnord { get; set; }
        public string Prcdc { get; set; }
        public string Prprot { get; set; }
        public decimal? Prcostomntc { get; set; }
        public string Prcomp { get; set; }
        public DateTime? Datasmsritardato { get; set; }
        public DateTime? Orasmsritardato { get; set; }
        public string Odlpadre { get; set; }
        public DateTime? Dataprevinmpf { get; set; }
        public decimal? Faxstatoditta { get; set; }
        public DateTime? Datafaxditta { get; set; }
        public string Statosms { get; set; }
        public DateTime? Datastatosms { get; set; }
        public DateTime? Orastatosms { get; set; }
        public string Statosms2 { get; set; }
        public DateTime? Datastatosms2 { get; set; }
        public DateTime? Orastatosms2 { get; set; }
        public DateTime? Datasopralluogo { get; set; }
        public DateTime? Orasopralluogo { get; set; }
        public string Sp { get; set; }
        public decimal? Impprevmntc { get; set; }
        public decimal? Pdl { get; set; }
        public string Mp2palbis { get; set; }
        public string Mp2palesito { get; set; }
        public string Mp2palesitobis { get; set; }
        public string Cdccliente { get; set; }
        public string Codmotivoannull { get; set; }
        public DateTime? Dataautproc { get; set; }
        public string Clienteticket { get; set; }
        public string Provenienza { get; set; }
        public string Rdimadre { get; set; }
        public string Descrizionebreve { get; set; }
        public string Notecliente { get; set; }
        public string Danno { get; set; }
        public string Utentechiamata { get; set; }
        public string Codiceavviso { get; set; }
        public string Esitosap { get; set; }
        public string Mailrich { get; set; }
        public string Sicurezza { get; set; }
        public string Competenza { get; set; }
        public string Motivochiusura { get; set; }
        public string InFranchigia { get; set; }
        public string Neve { get; set; }
        public string Stanza { get; set; }
        public string Statosap { get; set; }
        public string Noteapprovazione { get; set; }
        public string Codservizio { get; set; }
        public string Origineinserimento { get; set; }
        public decimal? Tmi { get; set; }
        public decimal? Tmf { get; set; }
        public string State { get; set; }
        public string Urgorigine { get; set; }
        public string Subrichiedente { get; set; }
        public string Idcontesto { get; set; }
        public string Gestitocentrale { get; set; }
        public string Indirizzointervento { get; set; }
        public int? Idworeqstato { get; set; }
        public string Edificio { get; set; }
        public string Vano { get; set; }
        public string Livello { get; set; }
        public string Ala { get; set; }
        public string DestinazioneUso { get; set; }
        public string Complesso { get; set; }
    }
}
